import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Store and Studio are Separated
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
